# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sabrine Labbadi
title: Software Engineering Student
email: labadi.sabrine@gmail.com
website: github.com/SabrineLabbadi/onlineCV

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  SabrineLabbadi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: labbadi-sabrine
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <br/><br/>
  Detail-oriented individual with exceptional multi-tasking and time management skills, looking for an End of Studies Internship “PFE” that will allow me to utilize my problem-solving skills to further develop my abilities in the field of computer science.
  <br/><br/>
  I am most skilled in: <mark>Java</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ISI Ariana
        link: www.isi.rnu.tn
        # link_text: boringcompany.com
        sub_title: Software Programmer Intern
        caption: August 2020 - October 2020
        quote: >
          The Higher Institute of Computer Science or ISI is a higher school located in Ariana and attached to the University of Tunis - El Manar.
        description: | # this will include new lines to allow paragraphs
            Working on a Machine Learning example using Andrea Lancichinetti’s Benchmarks for testing community detection algorithms on directed and weighted graphs with overlapping communities. The goal is to convert the algorithm from giving one graph for the whole data to divided graphs showing the adding of data from a moment to another. Tasks include code development, code reviews, writing and executing test procedures, tool development, as well as other software development activities.

      - layout: left
        title: IREX Tunis
        link: www.irex.org
        # link_text: boringcompany.com
        sub_title: Program Assistant
        caption: May 2019 - September 2019
        quote: >
          IREX is an international non-profit organization offering innovative programs to promote positive and lasting change on a global scale.
        description: | # this will include new lines to allow paragraphs
            - Answer phone calls and emails
            - Assist with administrative duties such as filing and copying
            - Translate program-related documents (English, French, and Arabic)
            - Provide a full range of logistics/arrangements and administrative program support
            
      - layout: left
        title: SIMAC Tunis
        link: www.simac.tn
        # link_text: boringcompany.com
        sub_title: Mobile App Developer Intern
        caption: February 2018 - June 2018
        quote: >
          SIMAC is a computer engineering company operating in the field of computer solutions since 1984 and is part of the SCET Tunisia group.
        description: | # this will include new lines to allow paragraphs
            - ADesign and development of a hybrid mobile application of physical inventory with Java on JDeveloper Software by Oracle
            - Work with other team members to learn, introduce and share development frameworks, tools, processes and best practices
            - Establish effective relationships with team members by fostering teamwork and a collaborative work environment

      - layout: left
        title: Kirkwood Community College, Iowa, USA
        link: www.kirkwood.edu
        # link_text: boringcompany.com
        sub_title: Web Designer Intern
        caption: January 2017 - May 2017
        quote: >
          Kirkwood Community College is accredited by the Higher Learning Commission (HLC) and offers over 120 different degrees, diplomas, and certifications.
        description: | # this will include new lines to allow paragraphs
            - Study of the needs of the client
            - Design of the website using Photoshop and an online tool: www.draw.io
            - Website development using WordPress CMS and WampServer
            - Work as part of scrum team using Agile development methodology
            - Work in an Agile development environment, produce modular and robust software systems
            
      - layout: left
        title: AppsFactor Technology Bizerte
        link: appsfactor.business.site
        # link_text: boringcompany.com
        sub_title: Web Developer Intern
        caption: January 2016 - February 2016
        quote: >
          Created in 2012, AppsFactor specializes in the development and implementation of advanced web solutions.
        description: | # this will include new lines to allow paragraphs
            - Configuration of a local database by WampServer
            - Design and development of a website for a company of architecture using WordPress
            - Preparing a documentation for the client
            - Host of the website: handasa.appsfactor-technology.com using FileZilla
            
      - layout: left
        title: Housing Bank BH Bizerte
        link: www.bh.com.tn
        # link_text: boringcompany.com
        sub_title: Technician Intern
        caption: January 2015 - February 2016
        quote: >
          BH Bank, formerly Banque de l'Habitat, is a Tunisian bank whose pioneering activity concerns real estate credit.
        description: | # this will include new lines to allow paragraphs
            - Installation of the Windows XP operating system
            - Creation of simple websites based on HTML and CSS
            - Text typing on Microsoft Word.
                                    
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ISI Ariana
        caption: 2018 - present
        sub_title: Engineering Degree in Computer Science
        quote: >
          The Higher Institute of Computer Science or ISI is a higher school located in Ariana and attached to the University of Tunis - El Manar.
        description: | # this will include new lines to allow paragraphs
          Focus: Software Development Engineering 
      
      - layout: left
        title: Kirkwood Community College, Iowa, USA
        caption: 2016 - 2017
        sub_title: College Certificates
        quote: >
          Kirkwood Community College is accredited by the Higher Learning Commission (HLC) and offers over 120 different degrees, diplomas, and certifications.
        description: | # this will include new lines to allow paragraphs
            - Java Programming Certificate
            - .Net programming Certificate
            - Web Development Certificate
            - Mobile App Development Certificate

      - layout: left
        title: ISET Bizerte
        caption: 2014 - 2018
        sub_title: Degree of Applied License in Computer Technologies
        quote: >
          ISET Bizerte is a public scientific and technological establishment. Its main mission is to contribute to socio-economic development and technology transfer in the Bizerte region as well as to strengthen the employability and professional integration of higher education graduates.
        description: | # this will include new lines to allow paragraphs
          Focus: Computer Software Development

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my highlights are:
      - Hult Prize Competitor in Tunis El Manar Campus
      - Google Club Vice-President at ISET Bizerte
      - Dean’s List and Honors Project in Kirkwood Community College
      - Outstanding International Student Award in Kirkwood Community College
      - Thomas Jefferson Scholarship Program alumna, sponsored by the US department of States
      - Multiple Soft Skills: analysis, conceptual skills, brainstorming, decision-making, collaboration, communication, leadership

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
